export const tags = [
  { value: "react", label: "react" },
  { value: "graphql", label: "graphql" },
  { value: "javascript", label: "javascript" },
  { value: "server", label: "server" },
  { value: "politics", label: "politics" },
  { value: "programming", label: "programming" },
  { value: "technology", label: "technology" },
  { value: "football", label: "football" },
  { value: "prisma", label: "prisma" },
  { value: "cookie", label: "cookie" },
  { value: "math", label: "math" },
  { value: "ai", label: "ai" },
  { value: "google", label: "google" },
  { value: "facebook", label: "facebook" },
  { value: "sports", label: "sports" },
  { value: "economics", label: "economics" },
  { value: "science", label: "science" },
  { value: "war", label: "war" },
  { value: "startup", label: "startup" },
  { value: "finance", label: "finance" },
  { value: "product", label: "product" },
  { value: "design", label: "design" },
];
